In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=2b08cc17c4806ee05e104b028952a497ea2419401053c5aa6df20aa9712609d1
  Stored in directory: /root/.cache/pip/wheels/cd/ef/ae/073b491b14d25e2efafcffca9e16b2ee6d114ec5c643ba4f06
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [9]:
from word2number import w2n

In [10]:
df = pd.read_csv(r'/content/car price prediction.csv')
df.head()

,normalized-losses,num-of-doors,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,89.10,four,185.922,65.835,53.559,3131,six,171,3.27,3.35,9.2,156,5200,20,24
1,NaN,four,196.911,67.716,58.113,3430,four,152,3.70,3.52,21.0,95,4150,25,25
2,NaN,four,196.911,67.716,58.113,3230,four,120,3.46,3.19,8.4,97,5000,19,24
3,190.08,two,175.032,64.152,53.757,2395,four,108,3.50,2.80,8.8,101,5800,23,29
4,126.72,two,163.647,63.162,53.955,1889,four,97,3.15,3.29,9.4,69,5200,31,37

In [11]:
df['num-of-doors'] = df['num-of-doors'].fillna('Zero')

In [12]:
df

,normalized-losses,num-of-doors,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,89.10,four,185.922,65.835,53.559,3131,six,171,3.27,3.35,9.2,156,5200,20,24
1,NaN,four,196.911,67.716,58.113,3430,four,152,3.70,3.52,21.0,95,4150,25,25
2,NaN,four,196.911,67.716,58.113,3230,four,120,3.46,3.19,8.4,97,5000,19,24
3,190.08,two,175.032,64.152,53.757,2395,four,108,3.50,2.80,8.8,101,5800,23,29
4,126.72,two,163.647,63.162,53.955,1889,four,97,3.15,3.29,9.4,69,5200,31,37
5,NaN,four,200.574,70.983,55.935,3740,eight,234,3.46,3.10,8.3,155,4750,16,18
6,140.58,two,178.497,69.795,50.292,3685,eight,234,3.46,3.10,8.3,155,4750,16,18
7,NaN,two,157.707,63.558,55.044,2254,four,109,3.19,3.40,8.5,90,5500,24,29
8,148.50,two,184.734,65.835,55.539,2707,four,121,2.54,2.07,9.3,110,5250,21,28
9,100.98,four,170.280,64.746,51.975,2145,four,108,3.62,2.64,9.5,82,4800,32,37
10,100.98,four,170.280,64.746,53.757,2385,four,108,3.62,2.64,9.0,82,4800,24,25
11,156.42,four,190.773,70.686,55.143,2844,five,136,3.19,3.40,8.5,110,5500,19,25
12,90.09,four,164.637,63.756,52.470,2094,four,98,3.19,3.03,9.0,70,4800,38,47
13,159.39,two,155.727,63.162,50.292,2145,four,98,3.03,3.39,7.6,102,5500,24,30
14,102.96,two,157.509,63.558,53.559,1900,four,91,3.03,3.15,9.0,68,5000,31,38
15,253.44,two,164.043,63.360,50.886,2221,four,109,3.19,3.40,8.5,90,5500,24,29
16,86.13,two,157.113,62.964,53.955,1985,four,92,3.05,3.03,9.0,62,4800,35,39
17,162.36,four,174.834,65.538,53.757,2337,four,109,3.19,3.40,10.0,102,5500,24,30
18,159.39,four,184.833,67.716,56.133,3075,four,120,3.46,3.19,8.4,97,5000,19,24
19,93.06,four,169.983,64.845,55.143,2212,four,109,3.19,3.40,9.0,85,5250,27,34
20,73.26,four,186.912,66.528,56.925,3042,four,141,3.78,3.15,9.5,114,5400,24,28
21,92.07,four,188.991,69.597,58.113,3750,five,183,3.58,3.64,21.5,123,4350,22,25
22,104.94,four,171.666,64.548,54.153,2324,four,120,3.33,3.47,8.5,97,5200,27,34
23,120.78,four,163.647,63.162,53.955,1938,four,97,3.15,3.29,9.4,69,5200,31,37
24,126.72,two,163.647,63.162,53.955,1951,four,97,3.15,3.29,9.4,69,5200,31,37
25,146.52,four,155.727,63.162,50.094,1989,four,90,2.97,3.23,9.4,68,5500,31,38
26,132.66,two,174.438,64.944,52.470,2975,four,146,3.62,3.50,9.3,116,4800,24,30
27,146.52,four,155.727,63.162,50.094,1967,four,90,2.97,3.23,9.4,68,5500,31,38
28,192.06,two,168.993,67.221,49.203,3139,six,181,3.43,3.27,7.8,200,5200,17,23
29,101.97,four,186.912,66.528,55.638,2935,four,141,3.78,3.15,9.5,114,5400,24,28
30,102.96,two,157.509,63.558,53.559,1890,four,91,3.03,3.15,9.0,68,5000,30,31
31,93.06,four,169.983,64.845,55.143,2264,four,97,3.01,3.40,23.0,52,4800,37,46
32,NaN,four,195.030,70.191,55.737,3505,six,209,3.62,3.39,8.0,182,5400,15,20
33,102.96,four,184.734,65.835,55.539,2847,four,121,3.54,3.07,9.0,160,5500,19,26
34,92.07,two,185.625,69.597,54.351,3495,five,183,3.58,3.64,21.5,123,4350,22,25
35,127.71,two,176.022,65.835,53.163,2385,four,122,3.39,3.39,8.6,84,4800,26,32
36,93.06,four,169.983,64.845,55.143,2319,four,97,3.01,3.40,23.0,68,4500,37,42
37,64.35,four,173.844,65.835,54.351,2480,four,110,3.27,3.35,22.5,73,4500,30,33
38,NaN,four,178.398,66.231,54.549,2579,four,97,3.01,3.40,23.0,68,4500,33,38
39,152.46,four,165.627,63.162,50.292,2191,four,98,2.97,3.23,9.4,68,5500,31,38
40,NaN,two,171.468,65.637,49.698,2833,four,156,3.58,3.86,7.0,145,5000,19,24

In [13]:
df['num-of-doors'] = df['num-of-doors'].apply(w2n.word_to_num)
df

,normalized-losses,num-of-doors,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,89.10,4,185.922,65.835,53.559,3131,six,171,3.27,3.35,9.2,156,5200,20,24
1,NaN,4,196.911,67.716,58.113,3430,four,152,3.70,3.52,21.0,95,4150,25,25
2,NaN,4,196.911,67.716,58.113,3230,four,120,3.46,3.19,8.4,97,5000,19,24
3,190.08,2,175.032,64.152,53.757,2395,four,108,3.50,2.80,8.8,101,5800,23,29
4,126.72,2,163.647,63.162,53.955,1889,four,97,3.15,3.29,9.4,69,5200,31,37
5,NaN,4,200.574,70.983,55.935,3740,eight,234,3.46,3.10,8.3,155,4750,16,18
6,140.58,2,178.497,69.795,50.292,3685,eight,234,3.46,3.10,8.3,155,4750,16,18
7,NaN,2,157.707,63.558,55.044,2254,four,109,3.19,3.40,8.5,90,5500,24,29
8,148.50,2,184.734,65.835,55.539,2707,four,121,2.54,2.07,9.3,110,5250,21,28
9,100.98,4,170.280,64.746,51.975,2145,four,108,3.62,2.64,9.5,82,4800,32,37
10,100.98,4,170.280,64.746,53.757,2385,four,108,3.62,2.64,9.0,82,4800,24,25
11,156.42,4,190.773,70.686,55.143,2844,five,136,3.19,3.40,8.5,110,5500,19,25
12,90.09,4,164.637,63.756,52.470,2094,four,98,3.19,3.03,9.0,70,4800,38,47
13,159.39,2,155.727,63.162,50.292,2145,four,98,3.03,3.39,7.6,102,5500,24,30
14,102.96,2,157.509,63.558,53.559,1900,four,91,3.03,3.15,9.0,68,5000,31,38
15,253.44,2,164.043,63.360,50.886,2221,four,109,3.19,3.40,8.5,90,5500,24,29
16,86.13,2,157.113,62.964,53.955,1985,four,92,3.05,3.03,9.0,62,4800,35,39
17,162.36,4,174.834,65.538,53.757,2337,four,109,3.19,3.40,10.0,102,5500,24,30
18,159.39,4,184.833,67.716,56.133,3075,four,120,3.46,3.19,8.4,97,5000,19,24
19,93.06,4,169.983,64.845,55.143,2212,four,109,3.19,3.40,9.0,85,5250,27,34
20,73.26,4,186.912,66.528,56.925,3042,four,141,3.78,3.15,9.5,114,5400,24,28
21,92.07,4,188.991,69.597,58.113,3750,five,183,3.58,3.64,21.5,123,4350,22,25
22,104.94,4,171.666,64.548,54.153,2324,four,120,3.33,3.47,8.5,97,5200,27,34
23,120.78,4,163.647,63.162,53.955,1938,four,97,3.15,3.29,9.4,69,5200,31,37
24,126.72,2,163.647,63.162,53.955,1951,four,97,3.15,3.29,9.4,69,5200,31,37
25,146.52,4,155.727,63.162,50.094,1989,four,90,2.97,3.23,9.4,68,5500,31,38
26,132.66,2,174.438,64.944,52.470,2975,four,146,3.62,3.50,9.3,116,4800,24,30
27,146.52,4,155.727,63.162,50.094,1967,four,90,2.97,3.23,9.4,68,5500,31,38
28,192.06,2,168.993,67.221,49.203,3139,six,181,3.43,3.27,7.8,200,5200,17,23
29,101.97,4,186.912,66.528,55.638,2935,four,141,3.78,3.15,9.5,114,5400,24,28
30,102.96,2,157.509,63.558,53.559,1890,four,91,3.03,3.15,9.0,68,5000,30,31
31,93.06,4,169.983,64.845,55.143,2264,four,97,3.01,3.40,23.0,52,4800,37,46
32,NaN,4,195.030,70.191,55.737,3505,six,209,3.62,3.39,8.0,182,5400,15,20
33,102.96,4,184.734,65.835,55.539,2847,four,121,3.54,3.07,9.0,160,5500,19,26
34,92.07,2,185.625,69.597,54.351,3495,five,183,3.58,3.64,21.5,123,4350,22,25
35,127.71,2,176.022,65.835,53.163,2385,four,122,3.39,3.39,8.6,84,4800,26,32
36,93.06,4,169.983,64.845,55.143,2319,four,97,3.01,3.40,23.0,68,4500,37,42
37,64.35,4,173.844,65.835,54.351,2480,four,110,3.27,3.35,22.5,73,4500,30,33
38,NaN,4,178.398,66.231,54.549,2579,four,97,3.01,3.40,23.0,68,4500,33,38
39,152.46,4,165.627,63.162,50.292,2191,four,98,2.97,3.23,9.4,68,5500,31,38
40,NaN,2,171.468,65.637,49.698,2833,four,156,3.58,3.86,7.0,145,5000,19,24

In [14]:
import math
median_test_score = math.floor(df['bore'].mean())
median_test_score

3

In [15]:
dff = df['bore'].mean()
dff

np.float64(3.2990243902439027)

In [16]:
df['bore'] = df['bore'].fillna(dff)
df

,normalized-losses,num-of-doors,length,width,height,curb-weight,num-of-cylinders,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg
0,89.10,4,185.922,65.835,53.559,3131,six,171,3.27,3.35,9.2,156,5200,20,24
1,NaN,4,196.911,67.716,58.113,3430,four,152,3.70,3.52,21.0,95,4150,25,25
2,NaN,4,196.911,67.716,58.113,3230,four,120,3.46,3.19,8.4,97,5000,19,24
3,190.08,2,175.032,64.152,53.757,2395,four,108,3.50,2.80,8.8,101,5800,23,29
4,126.72,2,163.647,63.162,53.955,1889,four,97,3.15,3.29,9.4,69,5200,31,37
5,NaN,4,200.574,70.983,55.935,3740,eight,234,3.46,3.10,8.3,155,4750,16,18
6,140.58,2,178.497,69.795,50.292,3685,eight,234,3.46,3.10,8.3,155,4750,16,18
7,NaN,2,157.707,63.558,55.044,2254,four,109,3.19,3.40,8.5,90,5500,24,29
8,148.50,2,184.734,65.835,55.539,2707,four,121,2.54,2.07,9.3,110,5250,21,28
9,100.98,4,170.280,64.746,51.975,2145,four,108,3.62,2.64,9.5,82,4800,32,37
10,100.98,4,170.280,64.746,53.757,2385,four,108,3.62,2.64,9.0,82,4800,24,25
11,156.42,4,190.773,70.686,55.143,2844,five,136,3.19,3.40,8.5,110,5500,19,25
12,90.09,4,164.637,63.756,52.470,2094,four,98,3.19,3.03,9.0,70,4800,38,47
13,159.39,2,155.727,63.162,50.292,2145,four,98,3.03,3.39,7.6,102,5500,24,30
14,102.96,2,157.509,63.558,53.559,1900,four,91,3.03,3.15,9.0,68,5000,31,38
15,253.44,2,164.043,63.360,50.886,2221,four,109,3.19,3.40,8.5,90,5500,24,29
16,86.13,2,157.113,62.964,53.955,1985,four,92,3.05,3.03,9.0,62,4800,35,39
17,162.36,4,174.834,65.538,53.757,2337,four,109,3.19,3.40,10.0,102,5500,24,30
18,159.39,4,184.833,67.716,56.133,3075,four,120,3.46,3.19,8.4,97,5000,19,24
19,93.06,4,169.983,64.845,55.143,2212,four,109,3.19,3.40,9.0,85,5250,27,34
20,73.26,4,186.912,66.528,56.925,3042,four,141,3.78,3.15,9.5,114,5400,24,28
21,92.07,4,188.991,69.597,58.113,3750,five,183,3.58,3.64,21.5,123,4350,22,25
22,104.94,4,171.666,64.548,54.153,2324,four,120,3.33,3.47,8.5,97,5200,27,34
23,120.78,4,163.647,63.162,53.955,1938,four,97,3.15,3.29,9.4,69,5200,31,37
24,126.72,2,163.647,63.162,53.955,1951,four,97,3.15,3.29,9.4,69,5200,31,37
25,146.52,4,155.727,63.162,50.094,1989,four,90,2.97,3.23,9.4,68,5500,31,38
26,132.66,2,174.438,64.944,52.470,2975,four,146,3.62,3.50,9.3,116,4800,24,30
27,146.52,4,155.727,63.162,50.094,1967,four,90,2.97,3.23,9.4,68,5500,31,38
28,192.06,2,168.993,67.221,49.203,3139,six,181,3.43,3.27,7.8,200,5200,17,23
29,101.97,4,186.912,66.528,55.638,2935,four,141,3.78,3.15,9.5,114,5400,24,28
30,102.96,2,157.509,63.558,53.559,1890,four,91,3.03,3.15,9.0,68,5000,30,31
31,93.06,4,169.983,64.845,55.143,2264,four,97,3.01,3.40,23.0,52,4800,37,46
32,NaN,4,195.030,70.191,55.737,3505,six,209,3.62,3.39,8.0,182,5400,15,20
33,102.96,4,184.734,65.835,55.539,2847,four,121,3.54,3.07,9.0,160,5500,19,26
34,92.07,2,185.625,69.597,54.351,3495,five,183,3.58,3.64,21.5,123,4350,22,25
35,127.71,2,176.022,65.835,53.163,2385,four,122,3.39,3.39,8.6,84,4800,26,32
36,93.06,4,169.983,64.845,55.143,2319,four,97,3.01,3.40,23.0,68,4500,37,42
37,64.35,4,173.844,65.835,54.351,2480,four,110,3.27,3.35,22.5,73,4500,30,33
38,NaN,4,178.398,66.231,54.549,2579,four,97,3.01,3.40,23.0,68,4500,33,38
39,152.46,4,165.627,63.162,50.292,2191,four,98,2.97,3.23,9.4,68,5500,31,38
40,NaN,2,171.468,65.637,49.698,2833,four,156,3.58,3.86,7.0,145,5000,19,24

In [17]:
df.columns

Index(['normalized-losses', 'num-of-doors', 'length', 'width', 'height',
       'curb-weight', 'num-of-cylinders', 'engine-size', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg'],
      dtype='object')

In [21]:
predictors = ['num-of-doors', 'city-mpg', 'peak-rpm']
x = df[predictors]
y = df['highway-mpg']

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
x_train.shape,x_test.shape

((32, 3), (9, 3))

In [24]:
y_train.shape,y_test.shape

((32,), (9,))

In [27]:
reg = LinearRegression()
model = reg.fit(x_train,y_train)
model.predict([[8,6,7]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([-6.52510653])

In [28]:
model.score(x_train,y_train)

0.9532356611000141

In [29]:
model.score(x_test,y_test)

0.9430460857488768